name: "sdd-workflow-kit"
description: "Check that SDD/agent scaffolding is in sync (sdd-kit check)."
inputs:
  project_root:
    description: "Project root to check"
    required: false
    default: "."
  config:
    description: "Path to .sddkit config"
    required: false
    default: ".sddkit/config.toml"
  fail_on_missing_config:
    description: "Fail if config is missing"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: "actions/setup-python@v6"
      with:
        python-version: "3.11"
    - name: "Install sddkit"
      shell: "bash"
      run: |
        python -m pip install --upgrade pip
        python -m pip install "${GITHUB_ACTION_PATH}"
    - name: "sdd-kit check"
      shell: "bash"
      run: |
        sdd-kit check --project "${{ inputs.project_root }}" --config "${{ inputs.config }}" --fail-on-missing-config="${{ inputs.fail_on_missing_config }}"

